version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  laravel:
    build: ./backend
    container_name: laravel
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000

  react:
    build: ./frontend-web
    container_name: react
    ports:
      - "3000:3000"

  node-server:
    build: ./node-server
    container_name: node-server
    ports:
      - "5000:5000"
    depends_on:
      - mysql

volumes:
  mysql_data:
