version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - db

  nodejs:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: nodejs_server
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./node-server:/usr/src/app
    ports:
      - "3000:3000" # node server listen 3000
    networks:
      - app-network

  db:
    image: mariadb:10.7 # atau mysql:8.0
    container_name: database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: monitoring
      MYSQL_USER: usermonitoring
      MYSQL_PASSWORD: secret123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
