version: "3.8"

services:
  db:
    image: mariadb:10.7
    container_name: database
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      MYSQL_DATABASE: monitoring
      MYSQL_USER: usermonitoring
      MYSQL_PASSWORD: secret123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  laravel:
    build: ./backend
    container_name: laravel
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - app-network

  react:
    build: ./frontend-web
    container_name: react
    env_file:
      - ./frontend-web/.env
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_URL: "https://api-monitoring.anggrisdev.my.id/api"

  node-server:
    build: ./node-server
    container_name: node-server
    env_file:
      - ./node-server/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_USER: usermonitoring
      DB_PASSWORD: secret123
      DB_NAME: monitoring
      DB_PORT: 3306
      PORT: 5000
      IDLE_MINUTES: 5

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
